### ISSUE TITLE
vlc not converting

### ISSUE THREAD

**Issue by steve6375** [BahKoo/ChocolateStore#11]
I don't think the URL is a problem one, so I am reporting it just in case.
https://chocolatey.org/packages/vlc
![image](https://cloud.githubusercontent.com/assets/1469350/26466032/3001f3c6-4185-11e7-83e7-2615af3422b0.png)

The script first tries just 'vlc' and got the .nupkg but then found that no .exe was downloaded so tries vlc.install.
So problem seems to be that a Setup.exe package was not made.
Should there be one to go with the .nupkg?
It mentions two letter language, but I can't see where it is used??

**Comment by BahKoo** [comment]
The authors of the VLC nuget package decided to embed to installer directly into the .nupkg file. So in this case there are no installers to store separately from the .nupkg file. ChocolateStore should work just fine with the 'vlc' package even though there is no installer to store separately. It's probably not safe to assume that a package will always have an installer to download. It's probably also not safe to assume that if a package doesn't work, that adding ".install" at the end will work. That is just a naming convention and not all packages follow that convention.

I recommend only installing packages that are known to work. In your case it would be:

- notepadplusplus.install
- produkey.install
- vlc

I will have to investigate whether it's possible to install dependent packages which would allow you to simply use the following packages:

- notepadplusplus
- produkey
- vlc

**Comment by steve6375** [comment]
Thanks for the explanation
I was made some false assumptions like there will always be a .exe and the installer version will always be xxxxx.install.
It is not a problem.
What I do is ask for a search string first (e.g. notepad) and the use clist to list all approved packages.
Then I ask them to type in the exact (case sensitive) name.
cheers and thanks for your help and patience.
Steve

**Comment by BahKoo** [comment]
No problem. I hope this solution works well for you. Good luck! Let me know if anything else comes up.
