### ISSUE TITLE
Can't download URLs with $variables in them

### ISSUE THREAD

**Issue by laggingreflex** [BahKoo/ChocolateStore#20]
Sorry for opening a lot of "can't download <package>" issues but I'm trying to open separate issues for what I think might be due to different reasons. 

This one I think is because there's variables in the URL that aren't expanded before downloading 

* Conemu uses a `$version` variable:

    **`chocolateyInstall.ps1`**
    ```ps
    $version = '18.02.06'
    ...
    $url = "https://github.com/Maximus5/ConEmu/releases/download/v$version/ConEmuSetup.$($version.replace('.','')).exe"
    ```

* Firefox uses a `$locale` variable:

    **`chocolateyInstall.ps1`**
    ```ps
    $locale = GetLocale -localeFile "$toolsPath\LanguageChecksums.csv" -product $softwareName
    ...
    Url = "https://download-installer.cdn.mozilla.net/pub/firefox/releases/58.0.2/win32/${locale}/Firefox%20Setup%2058.0.2.exe"
    ```

**Comment by sr258** [comment]
This seem to be the same issue as discussed [here](https://github.com/BahKoo/ChocolateStore/issues/4). The approach of replacing Install-ChocolateyPackage in the script with another command like Get-ChocolateyWebFile that downloads the file or somehow notifies C# of the urls looks promising. Not sure if eyaldar ever followed up on this.
