### ISSUE TITLE
ChocolateStore no longer works! Help!

### ISSUE THREAD

**Issue by steve6375** [BahKoo/ChocolateStore#23]
Now get SSL/TLS error 
![image](https://user-images.githubusercontent.com/1469350/78990708-0c675780-7b2f-11ea-923b-18e195135bbe.png)

**Comment by BahKoo** [comment]
I upgraded to .NET 4.7.2 That seems to fix the issue.

**Comment by steve6375** [comment]
Thanks - that's great.
Sorry to be a pain - could you point me to the compiled 32-bit exe please?
I dont have necessary skills\s/w to do a build.

**Comment by BahKoo** [comment]
Sorry I don't have the exe published anywhere. You'll need to open the solution in Visual Studio and build it OR find someone that can do it for you. You must have built it at some point.

**Comment by steve6375** [comment]
I got it from somewhere else, pre-made - can't remember who...
Could you email it to me pls?  steve@easy2boot.com   ;-)

**Comment by BahKoo** [comment]
https://send.firefox.com/download/3d430d12d5268a08/#3QVIZjWUG9jkWAkjSRdz1g
