### ISSUE TITLE
how this is working exactly ?

### ISSUE THREAD

**Issue by EmpiteLakshan** [BahKoo/ChocolateStore#6]
##Can you please tell me in detail how to do that? When I run tis in side bin folder ChocolateStore M:\Storechocolatey.org/api/v2/package/GoogleChrome it gave me a error message by telling “'ChocolateStore' is not recognized as an internal or external command, operable program or batch file.” 

##What are the arguments that I need to pass?

 ##And can you let me know where do I need to put this “ChocolateStore <directory> <url>” and what are the parameters do I need to insert (especially for <url>) 

##What is Ionic.Zip. What is that doing?

**Comment by BahKoo** [comment]
You need to compile the project with Visual Studio to create the ChocolateStore.exe executable. With a debug configuration, it should create this file in the `ChocolateStore\src\ChocolateStore\bin\Debug` folder.

There are 2 arguments to pass. The first is a local path in which to store the packages. The second is a URL to the hosted Chocolatey package.

Ionic.Zip is a Zip and Unzip library for C#. I use to to extract and repack the Chocolatey package with references to a locally cached installer.
