### ISSUE TITLE
Is it still working ?

### ISSUE THREAD

**Issue by redbaty** [BahKoo/ChocolateStore#7]
I mean, I tried running the example, but it won't download the chrome installer. So does it still works, and if yes what am I doing wrong ? 

Executing with:

ChocolateStore D:\Store http://chocolatey.org/api/v2/package/GoogleChrome/

**Comment by BahKoo** [comment]
I tried the GoogleChrome package and found the bug you encountered. URLs were being missed when they contained a space. I committed the fix. Please try it again and let me know if you have any problems.
