### ISSUE TITLE
+ characters missing from stored ChocolateyInstall script

### ISSUE THREAD

**Issue by FreakyDug** [BahKoo/ChocolateStore#8]
I am using ChocolateStore on the python2-x86_32 and python3-x86_32. In both the output package has lines that should look like this:

`$win32ProductName = $('^Python' + ' ' + [regex]::escape($version) + '$')`

changed into:

`$win32ProductName = $('^Python'  ' '  [regex]::escape($version)  '$')`

I had a look at the source, but I can't see any reason for this to be happening.

**Comment by BahKoo** [comment]
Thanks for reporting the issue. The problem was related to the file encoding. I committed a fix.

**Comment by FreakyDug** [comment]
That fix works for me, thanks!
